# Generated by Django 4.0.3 on 2022-03-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOutputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'model_output_type',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'storage_type',
            },
        ),
        migrations.CreateModel(
            name='TFModel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label_map_storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_model_label_map_storage', to='api.storage')),
                ('model_storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_model_storage', to='api.storage')),
                ('output_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modeloutputtype')),
            ],
            options={
                'db_table': 'tf_model',
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storagetype'),
        ),
    ]
