# Generated by Django 4.0.3 on 2022-03-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_storage_storage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='storage_type_id',
            new_name='storage_type',
        ),
        migrations.RenameField(
            model_name='tfmodel',
            old_name='label_map_storage_id',
            new_name='label_map_storage',
        ),
        migrations.RenameField(
            model_name='tfmodel',
            old_name='model_storage_id',
            new_name='model_storage',
        ),
        migrations.RenameField(
            model_name='tfmodel',
            old_name='output_type_id',
            new_name='output_type',
        ),
    ]
